import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function POST(request: Request) {
  const body = await request.json();

  // In production, proxy to Railway backend:
  // const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/generate-story`, {
  //   method: 'POST',
  //   headers: { 'Content-Type': 'application/json' },
  //   body: JSON.stringify(body),
  // });
  // return NextResponse.json(await res.json());

  // Stub: simulate delay and return mock script
  await new Promise((r) => setTimeout(r, 3000));

  const durationMinutes = body.duration_minutes || 3;
  const sceneCount = durationMinutes === 1 ? 6 : durationMinutes === 3 ? 8 : durationMinutes === 5 ? 10 : 12;

  const scenes = Array.from({ length: sceneCount }, (_, i) => ({
    title: `Scene ${i + 1}`,
    narrator_text: `Narrator text for scene ${i + 1} will be generated by the AI based on your story: "${body.title}".`,
    scene_description: `Visual description for scene ${i + 1} in ${body.genre} genre, ${body.style} style.`,
  }));

  return NextResponse.json({ success: true, scenes });
}
